/// Flutter icons TrailblazeIcons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
import 'package:flutter/widgets.dart';

class TrailblazeIcons {
  TrailblazeIcons._();

  static const _kFontFam = 'TrailblazeIcons';
  static const String? _kFontPkg = null;

  static const IconData directions_bike_gravel = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
