/// Flutter icons TrailblazeIcons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  TrailblazeIcons
///      fonts:
///       - asset: fonts/TrailblazeIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class TrailblazeIcons {
  TrailblazeIcons._();

  static const _kFontFam = 'TrailblazeIcons';
  static const String? _kFontPkg = null;

  static const IconData kDirectionsBikeGravel = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData kDirectionsBikeParks = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData kDirectionsWalkParks = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
